version: '3'

services:

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml

  ui:
    image: jc21/registry-ui
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - REGISTRY_HOST=registry:5000
      - REGISTRY_SSL=
      - REGISTRY_DOMAIN=
      - REGISTRY_STORAGE_DELETE_ENABLED=

volumes:
  data:
